var htmlCode = [
  { code: "<body>" },
  { code: '<div class="text-center"id="box">' },
  { code: "  <header>" },
  { code: "    <h1>Play Tic Tac Toe</h1>" },
  { code: "  </header>" },
  { code: '<div id="message"></div>' },
  { code: '  <ul id="gameBoard">' },
  { code: '    <li class="tic"id="0">#</li>' },
  { code: '    <li class="tic"id="1">#</li>' },
  { code: '    <li class="tic"id="2">#</li>' },
  { code: '    <li class="tic"id="3">#</li>' },
  { code: '    <li class="tic"id="4">#</li>' },
  { code: '    <li class="tic"id="5">#</li>' },
  { code: '    <li class="tic"id="6">#</li>' },
  { code: '    <li class="tic"id="7">#</li>' },
  { code: '    <li class="tic"id="8">#</li>' },
  { code: "  </ul>" },
  { code: '  <div class="clearfix"></div>' },
  { code: "<footer>" },
  { code: '  <button id="reset">Reset</button>' },
  { code: "</footer>" },
  { code: "</div>" },
  { code: "</body>" },
];

var cssCode = [
  { code: "body{" },
  { code: "  background: #212121;" },
  { code: "  color: #666;" },
  { code: "}" },
  { code: "h1{" },
  { code: "  text-align: center;" },
  { code: "  color: #fff;" },
  { code: "}" },
  { code: ".clearfix{" },
  { code: "  clear: both;" },
  { code: "}" },
  { code: "#box{" },
  { code: "  width: 350px;" },
  { code: "  overflow: auto;" },
  { code: "  margin: 40px auto;" },
  { code: "  background: #666;" },
  { code: "  padding-bottom: 40px;" },
  { code: "  border-radius: 10px;" },
  { code: "}" },
  { code: "#message{" },
  { code: "  background: #333;" },
  { code: "  color: #fff;" },
  { code: "}" },
  { code: "#gameBoard li{" },
  { code: "  float: left;" },
  { code: "  margin: 10px;" },
  { code: "  height: 70px;" },
  { code: "  width: 70px;" },
  { code: "  font-size: 50px;" },
  { code: "  background: #333;" },
  { code: "  color: #ccc;" },
  { code: "  list-style: none;" },
  { code: "  text-align: center;" },
  { code: "  border-radius: 5px;" },
  { code: "}" },
  { code: "#gameBoard li:hover, #reset:hover{" },
  { code: "  cursor: pointer;" },
  { code: "  background: #000;" },
  { code: "}" },
  { code: "#reset{" },
  { code: "  border: 0;" },
  { code: "  background: #444;" },
  { code: "  color: #fff;" },
  { code: "  width: 70%;" },
  { code: "  padding: 15px;" },
  { code: "  border-radius: 5px;" },
  { code: "}" },
  { code: ".o{" },
  { code: "  color: green !important;" },
  { code: "}" },
  { code: ".x{" },
  { code: "  color: red !important;" },
  { code: "}" },
  { code: "footer{" },
  { code: "  display: block;" },
  { code: "  text-align: center;" },
  { code: "  padding-top: 20px;" },
  { code: "}" },
];

var jsCode = [
  { code: "$(document).ready(function(){" },
  { code: 'var turns = ["#","#","#","#","#","#","+","#"];' },
  { code: 'var computerTurn = "";' },
  { code: 'var turn = "";' },
  { code: "var gameOn = false;" },
  { code: "var count = 0;" },
  {
    code: 'var startTurn = prompt("Choose Your Move", "Type X or O").toUpperCase();',
  },
  { code: "switch (startTurn) {" },
  { code: '    case "X":' },
  { code: '        computerTurn = "O";' },
  { code: '        turn = "X";' },
  { code: '        $("#message").html("Player " + turn + " gets to start!");' },
  { code: "        break;" },
  { code: '    case "O":' },
  { code: '        computerTurn = "X";' },
  { code: '        turn = "O";' },
  { code: '        $("#message").html("Player " + turn + " gets to start!");' },
  { code: "        break;" },
  { code: "    case null:" },
  { code: '        alert("Sorry. Please type X or O");' },
  { code: "        window.location.reload(true);" },
  { code: "    break;" },
  { code: "    default:" },
  { code: '        alert("Sorry. Please type X or O");' },
  { code: "        window.location.reload(true);" },
  { code: "        break;" },
  { code: "}" },
  { code: "function computersTurn() {" },
  { code: "    var taken = false;" },
  { code: "    while (taken === false && count !== 5) {" },
  { code: "        var computerMove = (Math.random() * 10).toFixed();" },
  { code: '        var move = $("#" + computerMove).text();' },
  { code: '        if (move === "#") {' },
  { code: '            $("#" + computerMove).text(computerTurn);' },
  { code: "            taken = true;" },
  { code: "            turns[computerMove] = computerTurn;" },
  { code: "        }" },
  { code: "    }" },
  { code: "}" },
  { code: "function playerTurn (turn, id){" },
  { code: '  var spotTaken = $("#"+id).text();' },
  { code: '  if (spotTaken ==="#"){' },
  { code: "    count++;" },
  { code: "    turns[id] = turn;" },
  { code: '    $("#"+id).text(turn);' },
  { code: "    winCondition(turns,turn);" },
  { code: "    if (gameOn === false){" },
  { code: "      computersTurn();" },
  { code: '      $("#message").html("Its " + turn +" turn.");' },
  { code: "      winCondition(turns, computerTurn);" },
  { code: "    }" },
  { code: "  }" },
  { code: "}" },
  { code: "function winCondition(trackMoves, currentMove) {" },
  {
    code: "    if (trackMoves[0] === currentMove && trackMoves[1] === currentMove && trackMoves[2] === currentMove) {",
  },
  { code: "        gameOn = true;" },
  { code: "        reset();" },
  { code: '        alert("Player " + currentMove + " wins!");' },
  {
    code: "    } else if (trackMoves[2] === currentMove && trackMoves[4] === currentMove && trackMoves[6] === currentMove) {",
  },
  { code: "        gameOn = true;" },
  { code: "        reset();" },
  { code: '        alert("Player " + currentMove + " wins!");' },
  {
    code: "    } else if (trackMoves[0] === currentMove && trackMoves[3] === currentMove && trackMoves[6] === currentMove) {",
  },
  { code: "        gameOn = true;" },
  { code: "        reset();" },
  { code: '        alert("Player " + currentMove + " wins!");' },
  {
    code: "    } else if (trackMoves[0] === currentMove && trackMoves[4] === currentMove && trackMoves[8] === currentMove) {",
  },
  { code: "        gameOn = true;" },
  { code: "        reset();" },
  { code: '        alert("Player " + currentMove + " wins!");' },
  {
    code: "    } else if (trackMoves[1] === currentMove && trackMoves[4] === currentMove && trackMoves[7] === currentMove) {",
  },
  { code: "        gameOn = true;" },
  { code: "        reset();" },
  { code: '        alert("Player " + currentMove + " wins!");' },
  {
    code: "    } else if (trackMoves[2] === currentMove && trackMoves[5] === currentMove && trackMoves[8] === currentMove) {",
  },
  { code: "        gameOn = true;" },
  { code: "        reset();" },
  { code: '        alert("Player " + currentMove + " wins!");' },
  {
    code: "    } else if (trackMoves[2] === currentMove && trackMoves[5] === currentMove && trackMoves[8] === currentMove) {",
  },
  { code: "        gameOn = true;" },
  { code: "        reset();" },
  { code: '        alert("Player " + currentMove + " wins!");' },
  {
    code: "    } else if (trackMoves[3] === currentMove && trackMoves[4] === currentMove && trackMoves[5] === currentMove) {",
  },
  { code: "        gameOn = true;" },
  { code: "        reset();" },
  { code: '        alert("Player " + currentMove + " wins!");' },
  {
    code: "    } else if (trackMoves[6] === currentMove && trackMoves[7] === currentMove && trackMoves[8] === currentMove) {",
  },
  { code: "        gameOn = true;" },
  { code: "        reset();" },
  { code: '        alert("Player " + currentMove + " wins!");' },
  { code: '    } else if(!(trackMoves.includes("#"))){' },
  { code: "       gameOn = true;" },
  { code: "      reset();" },
  { code: '      alert("It is a Draw!");' },
  { code: "    }﻿ else {" },
  { code: "        gameOn = false;" },
  { code: "    }" },
  { code: "}" },
  { code: '$(".tic").click(function(){' },
  { code: '  var slot = $(this).attr("id");' },
  { code: "  playerTurn(turn,slot);" },
  { code: "});" },
  { code: "function reset(){" },
  { code: '  turns = ["#","#","#","#","#","#","+","#"];' },
  { code: "  count = 0;" },
  { code: '  $(".tic").text("#");' },
  { code: "  gameOn = true;" },
  { code: "}" },
  { code: '$("#reset").click(function(){' },
  { code: "  reset();" },
  { code: "});" },
  { code: "})" },
];
