var htmlCode = [
  { code: "<body>" },
  { code: '<div class="text-center"id="box">' },
  { code: "  <header>" },
  { code: "    <h1>Play Tic Tac Toe</h1>" },
  { code: '    <div id="play">' },
  { code: "      <button>Play</button>" },
  { code: "    </div>" },
  { code: "  </header>" },
  { code: '<div id="message"></div>' },
  { code: '  <ul id="gameBoard">' },
  { code: '    <li class="tic"id="0">#</li>' },
  { code: '    <li class="tic"id="1">#</li>' },
  { code: '    <li class="tic"id="2">#</li>' },
  { code: '    <li class="tic"id="3">#</li>' },
  { code: '    <li class="tic"id="4">#</li>' },
  { code: '    <li class="tic"id="5">#</li>' },
  { code: '    <li class="tic"id="6">#</li>' },
  { code: '    <li class="tic"id="7">#</li>' },
  { code: '    <li class="tic"id="8">#</li>' },
  { code: "  </ul>" },
  { code: '  <div class="clearfix"></div>' },
  { code: "<footer>" },
  { code: '  <button id="reset">Reset</button>' },
  { code: "</footer>" },
  { code: "</div>" },
  { code: "</body>" },
];

var cssCode = [
  { code: "body{" },
  { code: "  background: #212121;" },
  { code: "  color: #666;" },
  { code: "}" },
  { code: "h1{" },
  { code: "  text-align: center;" },
  { code: "  color: #fff;" },
  { code: "}" },
  { code: ".clearfix{" },
  { code: "  clear: both;" },
  { code: "}" },
  { code: "#box{" },
  { code: "  width: 350px;" },
  { code: "  overflow: auto;" },
  { code: "  margin: 40px auto;" },
  { code: "  background: #666;" },
  { code: "  padding-bottom: 40px;" },
  { code: "  border-radius: 10px;" },
  { code: "}" },
  { code: "#play {" },
  { code: "  text-align: center;" },
  { code: "}" },
  { code: "#play button {" },
  { code: "  border: none;" },
  { code: "  background: #444;" },
  { code: "  color: #fff;" },
  { code: "  width: 40%;" },
  { code: "  padding: 10px;" },
  { code: "  border-radius: 5px;" },
  { code: "}" },
  { code: "#play button:hover {" },
  { code: "  cursor: pointer;" },
  { code: "  background: #000;" },
  { code: "}" },
  { code: "#message{" },
  { code: "  background: #333;" },
  { code: "  color: #fff;" },
  { code: "}" },
  { code: "#gameBoard li{" },
  { code: "  float: left;" },
  { code: "  margin: 10px;" },
  { code: "  height: 70px;" },
  { code: "  width: 70px;" },
  { code: "  font-size: 50px;" },
  { code: "  background: #333;" },
  { code: "  color: #ccc;" },
  { code: "  list-style: none;" },
  { code: "  text-align: center;" },
  { code: "  border-radius: 5px;" },
  { code: "}" },
  { code: "#gameBoard li:hover, #reset:hover{" },
  { code: "  cursor: pointer;" },
  { code: "  background: #000;" },
  { code: "}" },
  { code: "#reset{" },
  { code: "  border: 0;" },
  { code: "  background: #444;" },
  { code: "  color: #fff;" },
  { code: "  width: 70%;" },
  { code: "  padding: 15px;" },
  { code: "  border-radius: 5px;" },
  { code: "}" },
  { code: ".o{" },
  { code: "  color: green !important;" },
  { code: "}" },
  { code: ".x{" },
  { code: "  color: red !important;" },
  { code: "}" },
  { code: "footer{" },
  { code: "  display: block;" },
  { code: "  text-align: center;" },
  { code: "  padding-top: 20px;" },
  { code: "}" },
];

var jsCode = [
  { code: 'var turns = ["#", "#", "#", "#", "#", "#", "+", "#"];' },
  { code: 'var computerTurn = "";' },
  { code: 'var turn = "";' },
  { code: "var gameOn = false;" },
  { code: "var count = 0;" },
  { code: 'var startTurn = "";' },
  { code: "" },
  {
    code: 'document.querySelector("#play button").addEventListener("click", function () {',
  },
  { code: '  document.querySelector("#play").remove();' },
  {
    code: '  startTurn = prompt("Choose Your Move", "Type X or O").toUpperCase();',
  },
  { code: "  switch (startTurn) {" },
  { code: '    case "X":' },
  { code: '      computerTurn = "O";' },
  { code: '      turn = "X";' },
  { code: '      document.querySelector("#message").innerHTML =' },
  { code: '        "Player " + turn + " gets to start!";' },
  { code: "      break;" },
  { code: '    case "O":' },
  { code: '      computerTurn = "X";' },
  { code: '      turn = "O";' },
  { code: '      document.querySelector("#message").innerHTML =' },
  { code: '        "Player " + turn + " gets to start!";' },
  { code: "      break;" },
  { code: "    case null:" },
  { code: '      alert("Sorry. Please type X or O");' },
  { code: "      window.location.reload(true);" },
  { code: "      break;" },
  { code: "    default:" },
  { code: '      alert("Sorry. Please type X or O");' },
  { code: "      window.location.reload(true);" },
  { code: "      break;" },
  { code: "  }" },
  { code: "});" },
  { code: "" },
  { code: "function computersTurn() {" },
  { code: "  var taken = false;" },
  { code: "  while (taken === false && count !== 5) {" },
  { code: "    var computerMove = (Math.random() * 10).toFixed();" },
  { code: "    var move = document.getElementById(computerMove).textContent;" },
  { code: '    if (move === "#") {' },
  {
    code: "      document.getElementById(computerMove).textContent = computerTurn;",
  },
  { code: "      taken = true;" },
  { code: "      turns[computerMove] = computerTurn;" },
  { code: "    }" },
  { code: "  }" },
  { code: "}" },
  { code: "" },
  { code: "function playerTurn(turn, id) {" },
  { code: "  var spotTaken = document.getElementById(id).textContent;" },
  { code: '  if (spotTaken === "#") {' },
  { code: "    count++;" },
  { code: "    turns[id] = turn;" },
  { code: "    document.getElementById(id).textContent = turn;" },
  { code: "    winCondition(turns, turn);" },
  { code: "    if (gameOn === false) {" },
  { code: "      computersTurn();" },
  { code: '      document.querySelector("#message").innerHTML =' },
  { code: '        "Its " + turn + "s turn.";' },
  { code: "      winCondition(turns, computerTurn);" },
  { code: "    }" },
  { code: "  }" },
  { code: "}" },
  { code: "" },
  { code: "function winCondition(trackMoves, currentMove) {" },
  { code: "  if (" },
  { code: "    trackMoves[0] === currentMove &&" },
  { code: "    trackMoves[1] === currentMove &&" },
  { code: "    trackMoves[2] === currentMove" },
  { code: "  ) {" },
  { code: "    gameOn = true;" },
  { code: "    reset();" },
  { code: '    alert("Player " + currentMove + " wins!");' },
  { code: "  } else if (" },
  { code: "    trackMoves[2] === currentMove &&" },
  { code: "    trackMoves[4] === currentMove &&" },
  { code: "    trackMoves[6] === currentMove" },
  { code: "  ) {" },
  { code: "    gameOn = true;" },
  { code: "    reset();" },
  { code: '    alert("Player " + currentMove + " wins!");' },
  { code: "  } else if (" },
  { code: "    trackMoves[0] === currentMove &&" },
  { code: "    trackMoves[3] === currentMove &&" },
  { code: "    trackMoves[6] === currentMove" },
  { code: "  ) {" },
  { code: "    gameOn = true;" },
  { code: "    reset();" },
  { code: '    alert("Player " + currentMove + " wins!");' },
  { code: "  } else if (" },
  { code: "    trackMoves[0] === currentMove &&" },
  { code: "    trackMoves[4] === currentMove &&" },
  { code: "    trackMoves[8] === currentMove" },
  { code: "  ) {" },
  { code: "    gameOn = true;" },
  { code: "    reset();" },
  { code: '    alert("Player " + currentMove + " wins!");' },
  { code: "  } else if (" },
  { code: "    trackMoves[1] === currentMove &&" },
  { code: "    trackMoves[4] === currentMove &&" },
  { code: "    trackMoves[7] === currentMove" },
  { code: "  ) {" },
  { code: "    gameOn = true;" },
  { code: "    reset();" },
  { code: '    alert("Player " + currentMove + " wins!");' },
  { code: "  } else if (" },
  { code: "    trackMoves[2] === currentMove &&" },
  { code: "    trackMoves[5] === currentMove &&" },
  { code: "    trackMoves[8] === currentMove" },
  { code: "  ) {" },
  { code: "    gameOn = true;" },
  { code: "    reset();" },
  { code: '    alert("Player " + currentMove + " wins!");' },
  { code: "  } else if (" },
  { code: "    trackMoves[2] === currentMove &&" },
  { code: "    trackMoves[5] === currentMove &&" },
  { code: "    trackMoves[8] === currentMove" },
  { code: "  ) {" },
  { code: "    gameOn = true;" },
  { code: "    reset();" },
  { code: '    alert("Player " + currentMove + " wins!");' },
  { code: "  } else if (" },
  { code: "    trackMoves[3] === currentMove &&" },
  { code: "    trackMoves[4] === currentMove &&" },
  { code: "    trackMoves[5] === currentMove" },
  { code: "  ) {" },
  { code: "    gameOn = true;" },
  { code: "    reset();" },
  { code: '    alert("Player " + currentMove + " wins!");' },
  { code: "  } else if (" },
  { code: "    trackMoves[6] === currentMove &&" },
  { code: "    trackMoves[7] === currentMove &&" },
  { code: "    trackMoves[8] === currentMove" },
  { code: "  ) {" },
  { code: "    gameOn = true;" },
  { code: "    reset();" },
  { code: '    alert("Player " + currentMove + " wins!");' },
  { code: '  } else if (!trackMoves.includes("#")) {' },
  { code: "    gameOn = true;" },
  { code: "    reset();" },
  { code: '    alert("It is a Draw!");' },
  { code: "  } else {" },
  { code: "    gameOn = false;" },
  { code: "  }" },
  { code: "}" },
  { code: "" },
  {
    code: 'for (var i = 0; i < document.querySelectorAll(".tic").length; i++) {',
  },
  { code: "  document" },
  { code: '    .querySelectorAll(".tic")' },
  { code: '    [i].addEventListener("click", function (event) {' },
  { code: '      var slot = event.target.getAttribute("id");' },
  { code: "      playerTurn(turn, slot);" },
  { code: "    });" },
  { code: "}" },
  { code: "" },
  { code: "function reset() {" },
  { code: '  turns = ["#", "#", "#", "#", "#", "#", "+", "#"];' },
  { code: "  count = 0;" },
  { code: '  document.querySelector(".tic").textContent = "#";' },
  {
    code: '  for (var i = 0; i < document.querySelectorAll(".tic").length; i++) {',
  },
  { code: '    document.querySelectorAll(".tic")[i].textContent = "#";' },
  { code: "  }" },
  { code: "  gameOn = true;" },
  { code: "}" },
  { code: "" },
  {
    code: 'document.querySelector("#reset").addEventListener("click", function () {',
  },
  { code: "  reset();" },
  { code: "});" },
];
