var htmlCode = [
  {
    code: "<body>",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/body",
  },
  {
    code: "<div",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/div",
  },
  {
    code: '  class="text-center"',
    link: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes",
  },
  {
    code: '  id="box">',
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id",
  },
  {
    code: "    <header>",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header",
  },
  {
    code: "      <h1>Play Tic Tac Toe</h1>",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements",
  },
  {
    code: "      <div",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/div",
  },
  {
    code: '      id="play">',
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id",
  },
  {
    code: "        <button>Play</button>",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button",
  },
  {
    code: "      </div>",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/div",
  },
  {
    code: "    </header>",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header",
  },
  {
    code: "    <div",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/div",
  },
  {
    code: '      id="message">',
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id",
  },
  {
    code: "    </div>",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/div",
  },
  {
    code: "    <ul",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ul",
  },
  {
    code: '      id="gameBoard">',
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id",
  },
  {
    code: "      <li",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li",
  },
  {
    code: '        class="tic"',
    link: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes",
  },
  {
    code: '        id="0">',
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id",
  },
  {
    code: "        #</li>",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li",
  },
  {
    code: "      <li",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li",
  },
  {
    code: '        class="tic"',
    link: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes",
  },
  {
    code: '        id="1">',
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id",
  },
  {
    code: "      #</li>",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li",
  },
  {
    code: "      <li",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li",
  },
  {
    code: '        class="tic"',
    link: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes",
  },
  {
    code: '        id="2">',
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id",
  },
  {
    code: "      #</li>",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li",
  },
  {
    code: "      <li",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li",
  },
  {
    code: '        class="tic"',
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li",
  },
  {
    code: '        id="3">',
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id",
  },
  {
    code: "      #</li>",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li",
  },
  {
    code: "      <li",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li",
  },
  {
    code: '        class="tic"',
    link: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes",
  },
  {
    code: '        id="4">',
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id",
  },
  {
    code: "      #</li>",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li",
  },
  {
    code: "      <li",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li",
  },
  {
    code: '        class="tic"',
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li",
  },
  {
    code: '        id="5">',
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id",
  },
  {
    code: "      #</li>",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li",
  },
  {
    code: "      <li",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li",
  },
  {
    code: '        class="tic"',
    link: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes",
  },
  {
    code: '        id="6">',
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id",
  },
  {
    code: "      #</li>",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li",
  },
  {
    code: "      <li",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li",
  },
  {
    code: '        class="tic"',
    link: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes",
  },
  {
    code: '        id="7">',
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id",
  },
  {
    code: "        #</li>",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li",
  },
  {
    code: "      <li",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li",
  },
  {
    code: '        class="tic"',
    link: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes",
  },
  {
    code: '        id="8">',
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id",
  },
  {
    code: "        #</li>",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li",
  },
  {
    code: "    </ul>",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ul",
  },
  {
    code: "    <div",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/div",
  },
  {
    code: '      class="clearfix">',
    link: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes",
  },
  {
    code: "    </div>",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/div",
  },
  {
    code: "    <footer>",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/footer",
  },
  {
    code: "      <button",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button",
  },
  {
    code: '      id="reset">',
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id",
  },
  {
    code: "      Reset</button>",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button",
  },
  {
    code: "    </footer>",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/footer",
  },
  {
    code: "</div>",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/div",
  },
  {
    code: "</body>",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/body",
  },
];

var cssCode = [
  {
    code: "body{",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/body",
  },
  {
    code: "  background: #212121;",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/background",
  },
  {
    code: "  color: #666;",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/color_value",
  },
  { code: "}" },
  {
    code: "h1{",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements",
  },
  {
    code: "  text-align: center;",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/text-align",
  },
  {
    code: "  color: #fff;",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/color_value",
  },
  { code: "}" },
  { code: ".clearfix{" },
  {
    code: "  clear: both;",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/clear",
  },
  { code: "}" },
  { code: "#box{" },
  {
    code: "  width: 350px;",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/width",
  },
  {
    code: "  overflow: auto;",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/overflow",
  },
  {
    code: "  margin: 40px auto;",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/margin",
  },
  {
    code: "  background: #666;",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/background",
  },
  {
    code: "  padding-bottom: 40px;",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/padding-bottom",
  },
  {
    code: "  border-radius: 10px;",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/border-radius",
  },
  { code: "}" },
  { code: "#play {" },
  {
    code: "  text-align: center;",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/text-align",
  },
  { code: "}" },
  {
    code: "#play button {",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button",
  },
  {
    code: "  border: none;",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/border",
  },
  {
    code: "  background: #444;",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/background",
  },
  {
    code: "  color: #fff;",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/color_value",
  },
  {
    code: "  width: 40%;",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/width",
  },
  {
    code: "  padding: 10px;",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/padding",
  },
  {
    code: "  border-radius: 5px;",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/border-radius",
  },
  { code: "}" },
  {
    code: "#play button:hover {",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/:hover",
  },
  {
    code: "  cursor: pointer;",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/cursor",
  },
  {
    code: "  background: #000;",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/background",
  },
  { code: "}" },
  { code: "#message{" },
  {
    code: "  background: #333;",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/background",
  },
  {
    code: "  color: #fff;",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/color_value",
  },
  { code: "}" },
  {
    code: "#gameBoard li{",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li",
  },
  {
    code: "  float: left;",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/float",
  },
  {
    code: "  margin: 10px;",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/margin",
  },
  {
    code: "  height: 70px;",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/height",
  },
  {
    code: "  width: 70px;",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/width",
  },
  {
    code: "  font-size: 50px;",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/font-size",
  },
  {
    code: "  background: #333;",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/background",
  },
  {
    code: "  color: #ccc;",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/color_value",
  },
  {
    code: "  list-style: none;",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/list-style",
  },
  {
    code: "  text-align: center;",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/text-align",
  },
  {
    code: "  border-radius: 5px;",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/border-radius",
  },
  { code: "}" },
  {
    code: "#gameBoard li:hover, #reset:hover{",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/:hover",
  },
  {
    code: "  cursor: pointer;",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/cursor",
  },
  {
    code: "  background: #000;",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/background",
  },
  { code: "}" },
  { code: "#reset{" },
  {
    code: "  border: 0;",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/border",
  },
  {
    code: "  background: #444;",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/background",
  },
  {
    code: "  color: #fff;",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/color_value",
  },
  {
    code: "  width: 70%;",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/width",
  },
  {
    code: "  padding: 15px;",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/padding",
  },
  {
    code: "  border-radius: 5px;",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/border-radius",
  },
  { code: "}" },
  { code: ".o{" },
  {
    code: "  color: green !important;",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/color_value",
  },
  { code: "}" },
  { code: ".x{" },
  {
    code: "  color: red !important;",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/color_value",
  },
  { code: "}" },
  { code: "footer{" },
  {
    code: "  display: block;",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/display",
  },
  {
    code: "  text-align: center;",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/text-align",
  },
  {
    code: "  padding-top: 20px;",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/padding-top",
  },
  { code: "}" },
];

var jsCode = [
  { code: 'var turns = ["#", "#", "#", "#", "#", "#", "+", "#"];' },
  { code: 'var computerTurn = "";' },
  { code: 'var turn = "";' },
  { code: "var gameOn = false;" },
  { code: "var count = 0;" },
  { code: 'var startTurn = "";' },
  { code: "" },
  {
    code: 'document.querySelector("#play button").addEventListener("click", function () {',
  },
  { code: '  document.querySelector("#play").remove();' },
  {
    code: '  startTurn = prompt("Choose Your Move", "Type X or O").toUpperCase();',
  },
  { code: "  switch (startTurn) {" },
  { code: '    case "X":' },
  { code: '      computerTurn = "O";' },
  { code: '      turn = "X";' },
  { code: '      document.querySelector("#message").innerHTML =' },
  { code: '        "Player " + turn + " gets to start!";' },
  { code: "      break;" },
  { code: '    case "O":' },
  { code: '      computerTurn = "X";' },
  { code: '      turn = "O";' },
  { code: '      document.querySelector("#message").innerHTML =' },
  { code: '        "Player " + turn + " gets to start!";' },
  { code: "      break;" },
  { code: "    case null:" },
  { code: '      alert("Sorry. Please type X or O");' },
  { code: "      window.location.reload(true);" },
  { code: "      break;" },
  { code: "    default:" },
  { code: '      alert("Sorry. Please type X or O");' },
  { code: "      window.location.reload(true);" },
  { code: "      break;" },
  { code: "  }" },
  { code: "});" },
  { code: "" },
  { code: "function computersTurn() {" },
  { code: "  var taken = false;" },
  { code: "  while (taken === false && count !== 5) {" },
  { code: "    var computerMove = (Math.random() * 10).toFixed();" },
  { code: "    var move = document.getElementById(computerMove).textContent;" },
  { code: '    if (move === "#") {' },
  {
    code: "      document.getElementById(computerMove).textContent = computerTurn;",
  },
  { code: "      taken = true;" },
  { code: "      turns[computerMove] = computerTurn;" },
  { code: "    }" },
  { code: "  }" },
  { code: "}" },
  { code: "" },
  { code: "function playerTurn(turn, id) {" },
  { code: "  var spotTaken = document.getElementById(id).textContent;" },
  { code: '  if (spotTaken === "#") {' },
  { code: "    count++;" },
  { code: "    turns[id] = turn;" },
  { code: "    document.getElementById(id).textContent = turn;" },
  { code: "    winCondition(turns, turn);" },
  { code: "    if (gameOn === false) {" },
  { code: "      computersTurn();" },
  { code: '      document.querySelector("#message").innerHTML =' },
  { code: '        "Its " + turn + "s turn.";' },
  { code: "      winCondition(turns, computerTurn);" },
  { code: "    }" },
  { code: "  }" },
  { code: "}" },
  { code: "" },
  { code: "function winCondition(trackMoves, currentMove) {" },
  { code: "  if (" },
  { code: "    trackMoves[0] === currentMove &&" },
  { code: "    trackMoves[1] === currentMove &&" },
  { code: "    trackMoves[2] === currentMove" },
  { code: "  ) {" },
  { code: "    gameOn = true;" },
  { code: "    reset();" },
  { code: '    alert("Player " + currentMove + " wins!");' },
  { code: "  } else if (" },
  { code: "    trackMoves[2] === currentMove &&" },
  { code: "    trackMoves[4] === currentMove &&" },
  { code: "    trackMoves[6] === currentMove" },
  { code: "  ) {" },
  { code: "    gameOn = true;" },
  { code: "    reset();" },
  { code: '    alert("Player " + currentMove + " wins!");' },
  { code: "  } else if (" },
  { code: "    trackMoves[0] === currentMove &&" },
  { code: "    trackMoves[3] === currentMove &&" },
  { code: "    trackMoves[6] === currentMove" },
  { code: "  ) {" },
  { code: "    gameOn = true;" },
  { code: "    reset();" },
  { code: '    alert("Player " + currentMove + " wins!");' },
  { code: "  } else if (" },
  { code: "    trackMoves[0] === currentMove &&" },
  { code: "    trackMoves[4] === currentMove &&" },
  { code: "    trackMoves[8] === currentMove" },
  { code: "  ) {" },
  { code: "    gameOn = true;" },
  { code: "    reset();" },
  { code: '    alert("Player " + currentMove + " wins!");' },
  { code: "  } else if (" },
  { code: "    trackMoves[1] === currentMove &&" },
  { code: "    trackMoves[4] === currentMove &&" },
  { code: "    trackMoves[7] === currentMove" },
  { code: "  ) {" },
  { code: "    gameOn = true;" },
  { code: "    reset();" },
  { code: '    alert("Player " + currentMove + " wins!");' },
  { code: "  } else if (" },
  { code: "    trackMoves[2] === currentMove &&" },
  { code: "    trackMoves[5] === currentMove &&" },
  { code: "    trackMoves[8] === currentMove" },
  { code: "  ) {" },
  { code: "    gameOn = true;" },
  { code: "    reset();" },
  { code: '    alert("Player " + currentMove + " wins!");' },
  { code: "  } else if (" },
  { code: "    trackMoves[2] === currentMove &&" },
  { code: "    trackMoves[5] === currentMove &&" },
  { code: "    trackMoves[8] === currentMove" },
  { code: "  ) {" },
  { code: "    gameOn = true;" },
  { code: "    reset();" },
  { code: '    alert("Player " + currentMove + " wins!");' },
  { code: "  } else if (" },
  { code: "    trackMoves[3] === currentMove &&" },
  { code: "    trackMoves[4] === currentMove &&" },
  { code: "    trackMoves[5] === currentMove" },
  { code: "  ) {" },
  { code: "    gameOn = true;" },
  { code: "    reset();" },
  { code: '    alert("Player " + currentMove + " wins!");' },
  { code: "  } else if (" },
  { code: "    trackMoves[6] === currentMove &&" },
  { code: "    trackMoves[7] === currentMove &&" },
  { code: "    trackMoves[8] === currentMove" },
  { code: "  ) {" },
  { code: "    gameOn = true;" },
  { code: "    reset();" },
  { code: '    alert("Player " + currentMove + " wins!");' },
  { code: '  } else if (!trackMoves.includes("#")) {' },
  { code: "    gameOn = true;" },
  { code: "    reset();" },
  { code: '    alert("It is a Draw!");' },
  { code: "  } else {" },
  { code: "    gameOn = false;" },
  { code: "  }" },
  { code: "}" },
  { code: "" },
  {
    code: 'for (var i = 0; i < document.querySelectorAll(".tic").length; i++) {',
  },
  { code: "  document" },
  { code: '    .querySelectorAll(".tic")' },
  { code: '    [i].addEventListener("click", function (event) {' },
  { code: '      var slot = event.target.getAttribute("id");' },
  { code: "      playerTurn(turn, slot);" },
  { code: "    });" },
  { code: "}" },
  { code: "" },
  { code: "function reset() {" },
  { code: '  turns = ["#", "#", "#", "#", "#", "#", "+", "#"];' },
  { code: "  count = 0;" },
  { code: '  document.querySelector(".tic").textContent = "#";' },
  {
    code: '  for (var i = 0; i < document.querySelectorAll(".tic").length; i++) {',
  },
  { code: '    document.querySelectorAll(".tic")[i].textContent = "#";' },
  { code: "  }" },
  { code: "  gameOn = true;" },
  { code: "}" },
  { code: "" },
  {
    code: 'document.querySelector("#reset").addEventListener("click", function () {',
  },
  { code: "  reset();" },
  { code: "});" },
];
